-- local inProgress = false

-- local function getPlayerDiamonds(license)
--     local result = MySQL.Sync.fetchScalar('SELECT diamonds FROM player_diamonds WHERE license = @license', {
--         ['@license'] = license
--     })
--     return tonumber(result) or 0
-- end

-- RegisterCommand('purchase_package_tebex', function(source, args)
-- 	if source == 0 then
-- 		local dec = json.decode(args[1])
-- 		local tbxid = dec.transid
-- 		local packTab = {}
-- 		while inProgress do
-- 			Wait(1000)
-- 		end
-- 		inProgress = true
-- 		MySQL.query('SELECT * FROM codes WHERE code = @playerCode', {['@playerCode'] = tbxid}, function(result)
-- 			if result[1] then
-- 				local packagetable = json.decode(result[1].packagename)
-- 				packagetable[#packagetable+1] = dec.packagename
-- 				MySQL.update('UPDATE codes SET packagename = ? WHERE code = ?', {json.encode(packagetable), tbxid}, function(rowsChanged)
-- 					if rowsChanged > 0 then
-- 						SendToDiscord('purchase_logs','Purchase Logs', '`'..dec.packagename..'` was just purchased and inserted into the database under redeem code: `'..tbxid..'`.', 1752220)
--                     else
-- 						SendToDiscord('error_logs','Error Logs', '`'..tbxid..'` was not inserted into database. Please check for errors!', 15158332)
-- 					end
-- 				end)
-- 			else
-- 				packTab[#packTab+1] = dec.packagename
-- 				MySQL.insert("INSERT INTO codes (code, packagename) VALUES (?, ?)", {tbxid, json.encode(packTab)}, function(rowsChanged)
-- 					SendToDiscord('purchase_logs','Purchase Logs', '`'..dec.packagename..'` was just purchased and inserted into the database under redeem code: `'..tbxid..'`.', 1752220)
-- 					print('^2Purchase '..tbxid..' was succesfully inserted into the database.^0')
-- 				end)
-- 			end
-- 			inProgress = false
-- 		end)
-- 	else
-- 		print(GetPlayerName(source)..' tried to give themself a store code.')
-- 		SendToDiscord('exploit_logs','Attempted Exploit', GetPlayerName(source)..' tried to give themself a store code!', 15158332)
-- 	end
-- end, false)


-- lib.callback.register('bs_tebexwrapper:server:redeemCode', function(source, data)
--     local Player = GetPlayer(source)
--     if not Player then 
--         return { success = false, message = "Player data could not be found." } 
--     end
--     local license = Player.PlayerData.license
--     local codeToRedeem = data.code

--     if not codeToRedeem or codeToRedeem:gsub("%s", "") == "" then
--         return { success = false, message = "Please enter a code." }
--     end
--     local codeData = MySQL.Sync.fetchAll('SELECT * FROM codes WHERE UPPER(code) = UPPER(@code)', { 
--         ['@code'] = codeToRedeem 
--     })
--     if not codeData or not codeData[1] then
--         return { success = false, message = "This code is invalid or has already been used." }
--     end
--     local boughtPackages = json.decode(codeData[1].packagename)
--     local totalDiamondsToGive = 0
--     if boughtPackages and next(boughtPackages) ~= nil then
--         for _, packageName in ipairs(boughtPackages) do
--             if Config.Packages and Config.Packages[packageName] then
--                 totalDiamondsToGive = totalDiamondsToGive + Config.Packages[packageName]
--             else
--                 print(('[bs_tebexwrapper] WARNING: Player %s tried to redeem a code with an unconfigured package: "%s"'):format(license, packageName))
--             end
--         end
--     end
--     if totalDiamondsToGive <= 0 then
--         return { success = false, message = "The items in this code are no longer available. Please contact support." }
--     end
--     MySQL.Async.execute('INSERT INTO player_diamonds (license, diamonds) VALUES (@license, @amount) ON DUPLICATE KEY UPDATE diamonds = diamonds + @amount', {
--         ['@license'] = license,
--         ['@amount'] = totalDiamondsToGive
--     })
--     MySQL.Sync.execute('DELETE FROM codes WHERE code = @code', { ['@code'] = codeToRedeem })
--     local logMessage = ('Redeemed code "%s" for %d diamonds.'):format(codeToRedeem, totalDiamondsToGive)
--     createLog(source, 'redeem_code', logMessage)
-- 	SendToDiscord('redeem_logs','Redeem Code', 'logMessage', 65280) -- Green color for success
--     TriggerClientEvent('bs_tebexwrapper:client:refreshData', -1)
--     local newBalance = getPlayerDiamonds(license)
--     return {
--         success = true,
--         message = string.format("Success! You have redeemed %d Diamonds.", totalDiamondsToGive),
--         newBalance = newBalance
--     }
-- end)